name: bab
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^5.8.0+1
  flutter_native_splash: ^2.4.4
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  injectable: ^2.5.0
  injectable_generator: ^2.7.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  table_calendar: ^3.1.3
  timezone: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^2.5.8
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true
